### ISSUE TITLE
18.9 won't open again after 0.2.16

### ISSUE THREAD

**Issue by iMikeHimself** [Goldenfreddy0703/Otaku#24]
2022-10-12 16:58:09.800 T:30048   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2022-10-12 16:58:09.804 T:30332   ERROR: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.studios.white/.png
2022-10-12 16:58:09.915 T:15684   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Mick\AppData\Roaming\Kodi\addons\resource.images.busyspinners.basic\resources\gradient circle\
2022-10-12 16:58:09.915 T:15684   ERROR: XFILE::CDirectory::GetDirectory - Error getting special://home/addons/resource.images.busyspinners.basic/resources/gradient circle/
2022-10-12 16:58:09.915 T:22036   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Mick\AppData\Roaming\Kodi\addons\resource.images.busyspinners.basic\resources\gradient circle\
2022-10-12 16:58:09.915 T:22036   ERROR: XFILE::CDirectory::GetDirectory - Error getting special://home/addons/resource.images.busyspinners.basic/resources/gradient circle/
2022-10-12 16:58:13.155 T:19808   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Mick\AppData\Roaming\Kodi\addons\resource.images.busyspinners.basic\resources\gradient circle\
2022-10-12 16:58:13.155 T:19808   ERROR: XFILE::CDirectory::GetDirectory - Error getting special://home/addons/resource.images.busyspinners.basic/resources/gradient circle/
2022-10-12 16:58:20.470 T:30048   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.otaku/play/116674/2/]
2022-10-12 16:58:20.470 T:30048 WARNING: Attempt to set unplayable index 0
2022-10-12 16:58:38.317 T:30048   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2022-10-12 16:58:38.321 T:30332   ERROR: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.studios.white/.png
2022-10-12 16:58:38.434 T:22036   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Mick\AppData\Roaming\Kodi\addons\resource.images.busyspinners.basic\resources\gradient circle\
2022-10-12 16:58:38.434 T:22036   ERROR: XFILE::CDirectory::GetDirectory - Error getting special://home/addons/resource.images.busyspinners.basic/resources/gradient circle/
2022-10-12 16:58:38.646 T:2980   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'list' object has no attribute 'copy'
                                            Traceback (most recent call last):
                                              File "C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.otaku\default.py", line 846, in <module>
                                                router_process(control.get_plugin_url(), control.get_plugin_params())
                                              File "C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\router.py", line 70, in router_process
                                                return route_obj.func(payload, params)
                                              File "C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.otaku\default.py", line 833, in LIST_MENU
                                                MENU_ITEMS_SETTINGS = MENU_ITEMS.copy()
                                            AttributeError: 'list' object has no attribute 'copy'
                                            -->End of Python script error report<--
2022-10-12 16:58:38.732 T:21680   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.otaku/
2022-10-12 16:58:38.744 T:30048   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/) failed

**Comment by Gujal00** [comment]
The following syntax will not work on Python 2.7 which is used by Kodi versions 18 and below
```python
MENU_ITEMS_SETTINGS = MENU_ITEMS.copy()
```
Needs to change to the following for it to work on both Python 2 and 3
```python
MENU_ITEMS_SETTINGS = MENU_ITEMS[:]
```

**Comment by Goldenfreddy0703** [comment]
Hey sorry I've been really busy today but big thanks to @Gujal00 for providing a fix.

@iMikeHimself , test this next release and tell us if that has solved your issue.
